services:
  postgres:
    image: postgres:16
    container_name: nanoseller-postgres
    environment:
      POSTGRES_DB: nanoseller
      POSTGRES_USER: nanoseller
      POSTGRES_PASSWORD: nanoseller
    ports:
      - "5433:5432"
    volumes:
      - nanoseller_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nanoseller-redis
    ports:
      - "6379:6379"

volumes:
  nanoseller_pgdata:
